#
# Postfacto, a free, open-source and self-hosted retro tool aimed at helping
# remote teams.
#
# Copyright (C) 2016 - Present Pivotal Software, Inc.
#
# This program is free software: you can redistribute it and/or modify
#
# it under the terms of the GNU Affero General Public License as
#
# published by the Free Software Foundation, either version 3 of the
#
# License, or (at your option) any later version.
#
#
#
# This program is distributed in the hope that it will be useful,
#
# but WITHOUT ANY WARRANTY; without even the implied warranty of
#
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#
# GNU Affero General Public License for more details.
#
#
#
# You should have received a copy of the GNU Affero General Public License
#
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
source 'https://rubygems.org'

ruby '3.3.6'

gem 'rails'

gem 'activeadmin'
gem 'bcrypt'
gem 'devise'
gem 'friendly_id'
gem 'httpx'
gem 'inherited_resources'
gem 'jwt'
gem 'premailer-rails'
gem 'puma'
gem 'rack-cors', require: 'rack/cors'
gem 'rack-ssl'
gem 'sassc-rails'

# OpenTelemetry instrumentation
gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-semantic_conventions'

# Hotwire stack
gem 'turbo-rails'
gem 'stimulus-rails'
gem 'tailwindcss-rails'
gem 'importmap-rails'
gem 'sprockets-rails'

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'rspec_junit_formatter', require: false
  gem 'rubocop', require: false
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'simplecov-cobertura', require: false
  gem 'webmock'
  gem 'tzinfo-data'
  gem 'climate_control'
  gem 'action-cable-testing'
end

group :development do
  gem 'sqlite3'
  gem 'bullet'
  gem 'listen'
  gem 'web-console'
end

group :production do
  gem 'redis'
  gem 'pg'
end
